### ISSUE TITLE
IntegerDjangoChoices field not working

### ISSUE THREAD

**Issue by sanginovs** [blb-ventures/strawberry-django-plus#107]
Hi there
I am trying out this library and been enjoying it so far. 
I am running into this issue. Whenever i use IntegerChoicesField in my model and try to create a model using Django admin interface, it throws this error:

**Select a valid choice. 1 is not one of the available choices.**

<img width="575" alt="Screen Shot 2022-08-28 at 4 07 38 PM" src="https://user-images.githubusercontent.com/16856287/187098354-139953c5-becd-481b-9377-e42ea05c4ee7.png">

I am using the example code given:

```
class MyModel(models.Model):
  ...
  class IntegerEnum(models.IntegerChoices):
        FIRST = 1, "First Description"
        SECOND = 2, "Second Description"

    i_field = IntegerChoicesField(
        choices_enum=IntegerEnum,
        default=IntegerEnum.FIRST,
    )


```

TextChoicesField is working for me but IntegerChoicesField is throwing this error. appreciate any help

**Comment by bellini666** [comment]
Hey @sanginovs ,

This is actually an issue with https://github.com/bellini666/django-choices-field, which is also a project of mine =P

I'll try to transfer this issue there and take a look soon to see what is going on. Thanks for the report

**Comment by bellini666** [comment]
Hrm, it seems I cannot transfer outside of the organization...

Can you open an issue there?

**Comment by sanginovs** [comment]
sure. here we go: https://github.com/bellini666/django-choices-field/issues/5

**Comment by bellini666** [comment]
Thank you! I'll close this one
