### ISSUE TITLE
GlobalID vs ID scalar for Relay

### ISSUE THREAD

**Issue by LucasPickering** [blb-ventures/strawberry-django-plus#111]
First off, thanks for a great library, it's pretty easy to use and the documentation helps a lot. My question is: what was the reasoning behind the decision to generate a `GlobalID` scalar type for Relay node types rather than using the `ID` type built into the GraphQL spec? I'm wondering because `GlobalID` seems to prevent the usage of directives in Relay such as `@deleteEdge` and `@deleteRecord`, because those expect to be applied to a response field of type `ID` when the response is actually giving `GlobalID`.

For example, I have something like mutation:

```
mutation AssetList_deleteAssetMutation(
  $input: NodeInput!
  $connections: [GlobalID!]!
) {
  deleteBeta(input: $input) {
    id @deleteEdge(connections: $connections) @deleteRecord
  }
}
```

and I get this error from the Relay compiler:

```
Invalid use of @deleteEdge on field 'id'. Expected field type 'ID', got 'GlobalID!'
```

I couldn't find any other references to this issue, so I'm wondering if I'm just doing something wrong or misunderstanding something? Thanks!

**Comment by LucasPickering** [comment]
> Hey @LucasPickering ,
> 
> The main reason is because I wanted to create a custom structure for the global id: https://github.com/blb-ventures/strawberry-django-plus/blob/main/strawberry_django_plus/relay.py#L143
> 
> If I decided to override and use the same `ID` from strawberry it would force all ids to be parsed/serialized as a globalid, which has its own peculiarities.
> 
> Regarding your error, if you only use globalids you can probably override it to call it `ID`, as is described here: https://strawberry.rocks/docs/types/scalars#overriding-built-in-scalars . You just need to make sure you don't use `strawberry.ID` anywhere

Thank you! Here's what ended up working for me:

```
from strawberry_django_plus import gql
from strawberry.schema.types.scalar import DEFAULT_SCALAR_REGISTRY

schema = gql.Schema(
    query=Query,
    mutation=Mutation,
    scalar_overrides={gql.relay.GlobalID: DEFAULT_SCALAR_REGISTRY[gql.ID]},
)
```

**Comment by LucasPickering** [comment]
@bellini666 After working through this further, I realized the solution I posted above doesn't fully work. It successfully serializes IDs via the `GlobalID` method, and uses the `ID` type in the schema, but it falls back to `strawberry.ID` for deserialization. This results in an assertion error when the user makes a query with an ID parameter, because strawberry parses it into a plain string instead of a `GlobalID` value (the error is from [this line](https://github.com/blb-ventures/strawberry-django-plus/blob/v1.25/strawberry_django_plus/relay.py#L867)).

I tried creating my own scalar that uses the `ID` label in the SDL, but behaves like `GlobalID`, like so:

```
CustomID = gql.scalar(gql.relay.GlobalID, name="ID")

schema = gql.Schema(
    query=Query,
    mutation=Mutation,
    scalar_overrides={gql.relay.GlobalID: CustomID},
)
```

But this fails because the type `ID` is already taken by the built-in ID type: 

```TypeError: Mutation fields cannot be resolved. Scalar `ID` has already been registered```

Do you have any more suggestions for how to handle this? Do you know of any other apps using the Relay features here? I would think anyone else trying to do so would've run into this problem, so I'm curious how others have solved it.

**Comment by bellini666** [comment]
@LucasPickering you can probably override the `ID` key in [this dict](https://github.com/strawberry-graphql/strawberry/blob/main/strawberry/schema/types/scalar.py#L51) before creating the schema, to use your `CustomID`. I think it should work

**Comment by LucasPickering** [comment]
@bellini666 Sorry for the slow response on this, I took a break then it took me a while to find a working solution. In the end I had to fork this repo and make some hacks to get it to work. I had to modify the `GlobalID` type to replace the vanilla `ID` type. In addition, I had to modify some mutation logic to remove the `pk: ID` argument that gets created for each mutation, since that `ID` conflicts with the new one I'm trying to insert. Here's an example of the code changes I had to make in case anyone else wants to use this workaround: https://github.com/LucasPickering/strawberry-django-plus/commit/9b3c67528e6d71c2ec02e1cdbf2395e38debe443

I'm not sure if there's a good way to fix this in the library, since not everyone will want this functionality. But it's necessary to use Relay's directives, since those all require the `ID` type. So I'll leave this closed for now, since I'm not sure there's anything we can do.

**Comment by OdysseyJ** [comment]
same for me. thanks @LucasPickering

**Comment by OdysseyJ** [comment]
i faced same problem and fixed by your code!
thanks

**Comment by LucasPickering** [comment]
For anyone who runs into this, [this solution](https://github.com/blb-ventures/strawberry-django-plus/issues/166#issuecomment-1414420627) also works and doesn't require modifying the library, so it's much better.
