### ISSUE TITLE
strawberry.lazy issues (gql.django.connection, gql.django.field)

### ISSUE THREAD

**Issue by devkral** [blb-ventures/strawberry-django-plus#118]
I have some strange issues with the new lazy type (the LazyType works fine):

Code working:

``` python
...
class Foo
    @gql.django.field()
    def cluster(
        self: Content, info: Info
    )  -> Optional[gql.LazyType["ClusterNode", ".clusters"]]:
        if self.limited:
            return None
        # authorization often cannot be used, but it is ok, we have cached then
        res = (
            get_cached_result(info.context.request)["Cluster"]["objects"]
            .filter(id=self.cluster_id)
            .first()
        )
        if not res:
            self.cluster.limited = True
        return self.cluster
```

Code with lazy (not working)

``` python

if TYPE_CHECKING:
    from .clusters import ClusterNode
...
class Foo
    @gql.django.field()
    def cluster(
        self: Content, info: Info
    ) -> Optional[Annotated["ClusterNode", gql.lazy(".clusters")]]:
        if self.limited:
            return None
        # authorization often cannot be used, but it is ok, we have cached then
        res = (
            get_cached_result(info.context.request)["Cluster"]["objects"]
            .filter(id=self.cluster_id)
            .first()
        )
        if not res:
            self.cluster.limited = True
        return self.cluster
```

I get the error:
```
File "xxx/.venv/lib/python3.10/site-packages/graphql/type/definition.py", line 803, in fields
    raise cls(f"{self.name} fields cannot be resolved. {error}") from error
TypeError: Content fields cannot be resolved. Could not resolve the type of 'cluster'. Check that the class is accessible from the global module scope.
```

Do you need more informations?

**Comment by devkral** [comment]
Sry, I was in a hurry.

My question is:

Is my code incorrect (I implemented it according to the docs)?

Is there some problem with strawberry-django-plus with the new lazy type?

**Comment by bellini666** [comment]
Hi @devkral ,

Yeah, I had some issues at my end as well. I need to take a look because I may need to do something different to support it here.

I'll try to take a look this week or the beginning of next week

**Comment by devkral** [comment]
I think it's a similar issue to #129
The gql.django.field code path may need some updates

**Comment by bellini666** [comment]
Hey @devkral ,

strawberry had some changes regarding lazy handling, do you know if this issue still happens with its latest release? I unfortunately didn't have time to take a look at this yet

**Comment by devkral** [comment]
thx, the updates improved the situation drastically.
With some limitations I was able to use lazy.

The limitations were:
- circle lazy definitions are crashing (but work with strawberry.LazyType)  (strawberry issue?)
- Private fields were not working (but work with strawberry.LazyType) (strawberry issue?)

Here are the tracebacks
[traceback_circle_definition_lazy.txt](https://github.com/blb-ventures/strawberry-django-plus/files/9795593/traceback_circle_definition_lazy.txt)
[traceback_private_fields.txt](https://github.com/blb-ventures/strawberry-django-plus/files/9795594/traceback_private_fields.txt)

Here is a demonstration branch:
https://github.com/secretgraph/secretgraph/tree/bugreport/lazy_port_working_with_limitations

Shall I move the issue to strawberry?

**Comment by bellini666** [comment]
Nice! :)

Regarding the remaining errors:

- The circle definition seems to be an issue with this lib. Would be nice to have a minimal reproduction for it. Would you be able to provide one? If not, I can try to dig into it as soon as I have some time

- The private field I don't think it should work with lazy, because if the field is private it should not be exposed to the schema. In that case you can just `attr: "AttrType"` for typing. Or am I missing something in your implementation?
