### ISSUE TITLE
Using id in GlobalID directly

### ISSUE THREAD

**Issue by OdysseyJ** [blb-ventures/strawberry-django-plus#121]
Hi team!

is there any way to `GlobalID` using obj `id` directly (Not Encoded Value)?
thanks.

**Comment by bellini666** [comment]
Hi @OdysseyJ ,

This is actually a relay specification to allow identifying the object's type given the id only.

Is there a reason to why you need to use the id directly?

**Comment by OdysseyJ** [comment]
Hi @bellini666

ahh i'm pretty new in relay spec!
i didn't know relay spec need type/id pair in "ID" field.

sorry for bothering and thank you for maintaining amazing lib!
