### ISSUE TITLE
Context is `None` when using permission directives

### ISSUE THREAD

**Issue by furious-luke** [blb-ventures/strawberry-django-plus#13]
Hi there! Thanks for putting so much effort into a great set of additional utilities for Django and Strawberry. I've encountered an issue whereby when using the `IsAuthenticated` permission directive results in the following exception:

```
  File "/usr/local/lib/python3.9/site-packages/graphql/execution/execute.py", line 625, in await_result
    return_type, field_nodes, info, path, await result
  File "/code/strawberry/strawberry/extensions/directives.py", line 19, in resolve
    result = await await_maybe(_next(root, info, *args, **kwargs))
  File "/code/strawberry-django-plus/strawberry_django_plus/optimizer.py", line 506, in resolve
    ret = _next(root, info, *args, **kwargs)
  File "/code/strawberry-django-plus/strawberry_django_plus/directives.py", line 175, in resolve
    return _next(root, info, *args, **kwargs)
  File "/code/strawberry-django-plus/strawberry_django_plus/permissions.py", line 234, in resolve
    user = cast(UserType, context.request.user)
AttributeError: 'NoneType' object has no attribute 'request'
```

Breakpointing in to the code shows that `context` is `None`, which seems like it should never happen.

I don't believe my setup is anything unusual; I'm running latest versions of `strawberry`, `strawberry-graphql-django`, and `strawberry-django-plus`; I've created a very basic schema; I'm testing using the included GraphiQL interface. Without the permission directive everything works as expected, including using the context elsewhere in my code. However, when I include the permission directive, it fails.

Thanks!

**Comment by furious-luke** [comment]
After some digging I think I've found where the issue is; it seems to be related to the use of asynchronous consumers with Django Channels and Strawberry. Thanks anyway!

**Comment by bellini666** [comment]
Oh, nice to know in case I run into something like that in the future!

Other than that, feel free to open more issues if you find anything else!
