### ISSUE TITLE
DjangoOptimizerExtension not optimizing when fragments are used and field is queried twice

### ISSUE THREAD

**Issue by edomora97** [blb-ventures/strawberry-django-plus#144]
Given this schema (simplified from the demo):

<details>
<summary><code>schema.py</code></summary>

```python
from typing import List, cast

from strawberry_django_plus import gql
from strawberry_django_plus.directives import SchemaDirectiveExtension
from strawberry_django_plus.optimizer import DjangoOptimizerExtension

from .models import Issue, Tag


@gql.django.type(Issue)
class IssueType:
    name: gql.auto
    tags: List["TagType"]


@gql.django.type(Tag)
class TagType:
    name: gql.auto
    issues: List[IssueType]


@gql.type
class Query:
    issue_list: List[IssueType] = gql.django.field()


schema = gql.Schema(
    query=Query,
    extensions=[
        SchemaDirectiveExtension,
        DjangoOptimizerExtension,
    ],
)
```

</details>

And given these two _equivalent_ queries:

<details>
<summary><code>slow.graphql</code></summary>

```graphql
query Slow {
  issueList {
    name
    tags {
      ...A
    }
    tags {
      name
    }
  }
}

fragment A on TagType {
  issues {
    ...B
  }
}

fragment B on IssueType {
  name
}
```

</details>

<details>
<summary><code>fast.graphql</code> (obtained by clicking on "Merge fragments into query" in GraphiQL)</summary>

```graphql
query Fast {
  issueList {
    name
    tags {
      issues {
        name
      }
      name
    }
  }
}
```

</details>

Initializing the database with this queries:

<details>
<summary>Details</summary>

```sql
INSERT INTO demo_issue (id, name, priority)
VALUES (1, 'issue1', 1), (2, 'issue2', 2), (3, 'issue3', 3);

INSERT INTO demo_tag (id, name)
VALUES (1, 'tag1'), (2, 'tag2'), (3, 'tag3');

INSERT INTO demo_issue_tags (issue_id, tag_id)
VALUES (1, 1), (1, 2), (1, 3), (2, 1), (2, 2), (2, 3), (3, 1), (3, 2), (3, 3);
```

</details>

Slow is experiencing the N+1 queries problem, while Fast is not.

Using GraphiQL and the Django toolbar I can see that **Fast** is making 3 queries:

![image](https://user-images.githubusercontent.com/6685454/202849995-323d86fb-f79f-4a55-9d03-2a6688b413a6.png)

While **Slow** is making 11:

![image](https://user-images.githubusercontent.com/6685454/202850010-a403dba8-5640-4148-b06e-70a479b110a8.png)

Note that moving the field `name` from `issueList` into the fragment `A` doesn't trigger the issue.

**Comment by blueyed** [comment]
@edomora97 
btw/OT:

> Using GraphiQL and the Django toolbar

How does this work for you?
I'm using https://github.com/przemub/django-graphiql-strawberry-debug-toolbar, but despite the fix from https://github.com/przemub/django-graphiql-strawberry-debug-toolbar/pull/1 it appears to not be working for me anymore currently.

**Comment by bellini666** [comment]
Hey @edomora97 , thanks for reporting this.

The optimizer does take fragments into consideration, but your example might be hitting a corner case that it is not considering. The code that inspects the query is https://github.com/blb-ventures/strawberry-django-plus/blob/87fb0948f8ae9158a0884d21221a8ad7abf2a436/strawberry_django_plus/utils/inspect.py#L193, with the fragment handling being done in [this elif clause](https://github.com/blb-ventures/strawberry-django-plus/blob/87fb0948f8ae9158a0884d21221a8ad7abf2a436/strawberry_django_plus/utils/inspect.py#L227).

I'll try to take a look at that by the end of the week, but if you have time to take a look at this, feel free to open a PR that fixes it and I'll glagly review it :)

@blueyed this lib provides a [fix to the toolbar](https://github.com/blb-ventures/strawberry-django-plus/blob/main/strawberry_django_plus/middlewares/debug_toolbar.py#L100) to make it work, even with async views. Try using it: https://blb-ventures.github.io/strawberry-django-plus/debug-toolbar/
