### ISSUE TITLE
CUD mutations Input vs NodeInput

### ISSUE THREAD

**Issue by gersmann** [blb-ventures/strawberry-django-plus#146]
Hi @bellini666, quick question about the CUD mutations. They are expecting a `NodeInput` as input, but from the implementation I can see that both, `ID` and `GlobalID` cases are managed, when I tested this it worked fine with `ID`.

Would it make sense to update/relax the input type annotation?

**Comment by gersmann** [comment]
what I mean is this:
```
graphql.py:57: error: Argument 1 to "update" has incompatible type "Type[ReportInput]"; expected "Type[NodeInput]"  [arg-type]
Found 1 error in 1 file (checked 1 source file)
```
update_mutation works with a regular InputType, but I have to ignore the typecheck. Would it be possible to change:
```
def update(
    input_type: Type[NodeInput],
    *,
    ...
```
to 
```
def update(
    input_type: Type[InputType],
    *,
```
?

**Comment by gersmann** [comment]
It's not really important for me however, decided to use relay.InputNode.

**Comment by bellini666** [comment]
Hey @gersmann . Based on your last comment, can I close this issue?

**Comment by gersmann** [comment]
> Hey @gersmann . Based on your last comment, can I close this issue?

Yes sure, good with me.
