### ISSUE TITLE
Typing error on directives using permissions

### ISSUE THREAD

**Issue by darwinhace** [blb-ventures/strawberry-django-plus#15]
when I'm using IsAuthenticated() or HasPerm() my pycharm ide gives a warning

![image](https://user-images.githubusercontent.com/76155308/155658671-19228d57-30c3-4e55-9cae-597aa8271c40.png)

when I dig, directives only receive StrawberrySchemaDirective but permissions based on SchemaDirectiveResolver, maybe we can Union[SchemaDirectiveResolver, StrawberrySchemaDirective]

**Comment by bpeschier** [comment]
Had the same issue. Created a PR for the fix, which was to add the missing type annotation for the schema_directive decorator. #16

**Comment by bellini666** [comment]
So strange that `pyright` types it correctly.

Either way, thanks for the contribution @bpeschier , going to release the fix today with some other changes I'm doing.
