### ISSUE TITLE
Prefetch related selects all the fields on the model instead of the ones specified in the gql query

### ISSUE THREAD

**Issue by vitosamson** [blb-ventures/strawberry-django-plus#156]
Given a model setup like this:

```py
class Foo(Model):
    pass

class Bar(Model):
    field_1 = CharField()
    field_2 = CharField()
    foo = ForeignKey(Foo, related_name="bars")

```

and a corresponding schema:

```py
@gql.django.type(Foo)
class FooType:
    id: auto
    bars: "List[BarType]"

@gql.django.type(Bar)
class BarType:
    id: auto
```

when I make a query like

```graphql
{
  foo(id: 1) {
    bars {
      id
    }
  }
}
```

where it should only select `id` in the prefetch on the `Bar` model, the resulting query actually includes all of the fields on that model.

I tracked the issue down to these lines: https://github.com/blb-ventures/strawberry-django-plus/blob/a8f45e7fd276de5009d448c7e8579bf293419dbd/strawberry_django_plus/optimizer.py#L523-L525

When I step through with the debugger, before that line the prefetch query only includes the fields selected in the gql query (`id` and the related `foo_id`). At this point `to_prefetch[ao].queryset.query.deferred_loading` has the value `({'id', 'foo_id'}, False)`.

After that line, with `deferred_loading` set to `([], True)`, the prefetch query contains all of the fields on the model. If we're also querying other related models on `Bar`, then we lose all of their field selections as well and the whole rows are fetched from the database.

> Abort only optimization if one prefetch related was made for everything

I'm having trouble understanding what this means. Why are we aborting the `only` optimization on this prefetch, and how can I prevent that from happening? If I comment out the code I linked above, my query executes and returns as expected with the fields I specified.

**Comment by bellini666** [comment]
I found the issue here. The only abort should only be done when prefeching a string itself (which means "prefetch the whole model"), but it was being done  for every prefetch.

I'm releasing a fix atm

**Comment by vitosamson** [comment]
Awesome, thank you!
