### ISSUE TITLE
Cursor Pagination without relay

### ISSUE THREAD

**Issue by m4riok** [blb-ventures/strawberry-django-plus#157]
Hello and merry xmas.

I just finished an implementation of cursor pagination for a non-relay context and I encountered a couple of issues I would like to ask about and perhaps get a few pointers on a better implementation. Pagination was implemented using a modified version of [django-cursor-pagination](https://github.com/photocrowd/django-cursor-pagination) , sub-classing StrawberryDjangoField , implementing a generic type for the pagination result and a custom field function to return and pass options to  the instance of the sub classed  StrawberryDjangoField

**Field Implementation:**

```python
@strawberry.type
class PageInfo:
    has_next_page: bool
    has_previous_page: bool
    start_cursor: Optional[str]
    end_cursor: Optional[str]

E = TypeVar("E")
@strawberry.type
class CursorPaginatedList(Generic[E]):
    page_info: PageInfo
    items: List[E]

@strawberry.input
class CursorPaginationInput:
    first: Optional[int] = None
    last: Optional[int] = None
    before: Optional[str] = None
    after: Optional[str] = None

class CursoredGenericDjangoField(
    _StrawberryDjangoField
):
    def __init__(self, cursor_ordering=UNSET,  **kwargs):
        self.cursor_pagination = kwargs.pop('cursor_pagination',False)
        #remove other pagination and order if defined
        if self.cursor_pagination:
            kwargs.pop('order')
            kwargs.pop('pagination')
        super().__init__(**kwargs)

    @property
    def arguments(self) -> List[StrawberryArgument]:
        arguments = []
        if self.cursor_pagination:
            arguments.append(argument("cursor_pagination",CursorPaginationInput))
            arguments.append(argument("cursor_ordering",Optional[str]))
        return super().arguments + arguments

    @property
    def is_list(self):
        if self.cursor_pagination is UNSET or not self.cursor_pagination:
            return super().is_list
        return True

    @property
    def type(self) -> Union[StrawberryType, type]:
        return super().type

    @type.setter
    def type(self, type_: Any) -> None:
        super(CursoredGenericDjangoField, self.__class__).type.fset(self, type_)
        #store type and inner type to use in return of result and get_queryset to grab 
        #any get_queryset overload that exists on inner type definition
        if type_ is not None and self.cursor_pagination:
            self.paginated_type = type_
            self.inner_type = typing.get_args(type_)[0]


    #resolvers.resolve_result returns a coroutine which needs to be awaited so we can get a list and slice it
    #so this needs to be async. Could not figure out a better way to do this.
    async def rewrap_result(self,result,**kwargs):
        qls = list(await result)
        cp = kwargs.get('cursor_pagination',None)
        if cp and len(qls):
            page = self.paginator.page_from_list(qls,first=cp.first , last=cp.last , after=cp.after, before=cp.before)
            pi = PageInfo(
                has_next_page= page.has_next,
                has_previous_page= page.has_previous,
                start_cursor=page.paginator.cursor(page.items[0]),
                end_cursor=page.paginator.cursor(page.items[-1]),
            )
            res =  self.paginated_type(
                page_info=pi,
                items=page.items,
            )
        else:
            pi = PageInfo(
                has_next_page= False,
                has_previous_page= False,
                start_cursor=None,
                end_cursor=None,
            )
            res =  self.paginated_type(
                page_info=pi,
                items=qls,
            )
        return res

    def get_result(
        self,
        source: Optional[models.Model],
        info: Info,
        args: List[Any],
        kwargs: Dict[str, Any],
    ) -> Union[Awaitable[Any], Any]:
        if self.cursor_pagination:
            return self.rewrap_result(super().get_result(source , info , args , kwargs), **kwargs)
        return super().get_result(source , info , args , kwargs)        

    def paginate(self , qs , **kwargs):
        cp = kwargs.get('cursor_pagination')
        order = kwargs.get('cursor_ordering','id')
        self.paginator = CursorPaginator(qs, ordering=(order,'-id'))
        #Had to modify the paginator to split it's original page method into
        #two separate methods one adding filters to the queryset and another to slice the result
        #because resolvers.resolve_result returns a coroutine and not a queryset
        page = self.paginator.page_queryset(first=cp.first, after=cp.after , last=cp.last , before=cp.before)
        return page

    def get_queryset(self, queryset, info, order=UNSET, **kwargs):
        if self.cursor_pagination:
            inner_get_queryset = getattr(self.inner_type,"get_queryset",None)
            #Apply inner get queryset defined on the paginated type
            if inner_get_queryset:
                queryset = inner_get_queryset(queryset, info, **kwargs)
            #Get the queryset from super now so we get filtering on it
            queryset =  super().get_queryset(queryset, info, order=order, **kwargs)
            #Apply pagination and ordering or just ordering based on one 
            #unique field as required for cursor pagination
            if kwargs.get('cursor_pagination',None):
                queryset = self.paginate(queryset,**kwargs)
            else:
                ob = kwargs.get('cursor_ordering',None)
                if ob:
                    queryset = queryset.order_by(ob)
            return queryset
        return super().get_queryset(queryset, info, order=order, **kwargs)

#re-defining the field function would not be necessary if:
#  1) Any number of extra params would be passed to the constructor of the field class
#  2) a field_cls parameter would allow for selection of which class would be returned like with type
def field(
    resolver=None,
    *,
    name: Optional[str] = None,
    field_name: Optional[str] = None,
    is_subscription: bool = False,
    description: Optional[str] = None,
    permission_classes: Optional[List[Type[BasePermission]]] = None,
    deprecation_reason: Optional[str] = None,
    default: Any = dataclasses.MISSING,
    default_factory: Union[Callable[..., object], object] = dataclasses.MISSING,
    metadata: Optional[Mapping[Any, Any]] = None,
    directives: Optional[Sequence[object]] = (),
    pagination: Optional[bool] = UNSET,
    filters: Optional[type] = UNSET,
    order: Optional[type] = UNSET,
    only: Optional[TypeOrSequence[str]] = None,
    select_related: Optional[TypeOrSequence[str]] = None,
    prefetch_related: Optional[TypeOrSequence[PrefetchType]] = None,
    disable_optimization: bool = False,
    init: Literal[True, False, None] = None,
    #This was added to allow cursor_pagination=True to be passed to the instance
    #or any other parameter that we may require in other subclasses of StrawberryDjangoField
    **kwargs
) -> Any:

    f = CursoredGenericDjangoField(
       python_name=None,
       django_name=field_name,
       graphql_name=name,
       type_annotation=None,
       description=description,
       is_subscription=is_subscription,
       permission_classes=permission_classes or [],
       deprecation_reason=deprecation_reason,
       default=default,
       default_factory=default_factory,
       metadata=metadata,
       directives=directives,
       filters=filters,
       pagination=pagination,
       order=order,
       only=only,
       select_related=select_related,
       prefetch_related=prefetch_related,
       disable_optimization=disable_optimization,
       **kwargs
    )
    if resolver:
        f = f(resolver)
    return f

```
**Usage:**
```Python
@strawberry.type
class Query:
    paginated_list:  module.CursorPaginatedList[SomeType] = module.field(cursor_pagination=True , filters=SomeFilter)
```
Or CursorPaginatedList could be sub classed to add more fields to it.

**Issues:**

1. Is there any way to make the field function in this package more "generic" so it can instantiate any subclass of StrawberryDjangoField passing to it any number of extra arguments and leave it to the user to pop them so they don't get passed down the inheritance chain ? 
2. resolvers.resolve_result returns a coroutine which forced me to use the workarounds outlined in the comments and to modify the paginators functionality splitting the filtering on the queryset from the slicing of the result. Can you suggest any workaround on this? 
3. My initial instinct was to detect whether the type is a subclass of CursorPaginatedList and not have to pass a cursor_pagination=True to the constructor but I could not find a way to detect the type within the __init__ to disable default order and pagination. Also couldn't find a reliable way to detect  whether a type is a subclass for that matter. Any suggestions ?

**Enhancements:**

1.  While reading through the code to get hints for my implementation I noticed that it's very tightly coupled with the relay implementation which made it kind of hard to figure out which part needed to be re-implemented. Perhaps the relay implementation should be completely separate ?
2.  StrawberryDjangoField is a subclass of strawberry_django.field.StrawberryDjangoField which has multiple inheritance on the pagination , filter and ordering classes. It would be nice if a bare minimally working version of StrawberryDjangoField was provided so a user can do his own composition on the field choosing to use , not use or maybe replace  some of these classes. 

Thanks in advance for any comments or suggestions you may have on this.

**Comment by bellini666** [comment]
Hey @m4riok ,

First of all, for curiosity, why are you implementing your own "no relay" cursor pagination while it looks a lot like the relay one?

> 1. Is there any way to make the field function in this package more "generic" so it can instantiate any subclass of StrawberryDjangoField passing to it any number of extra arguments and leave it to the user to pop them so they don't get passed down the inheritance chain ?

We could probably receive an optional `field_type` keyword, which defaults to `StrawberryDjangoField` if not provided, and use it to instantiate the field. What do you think?

> 2. resolvers.resolve_result returns a coroutine which forced me to use the workarounds outlined in the comments and to modify the paginators functionality splitting the filtering on the queryset from the slicing of the result. Can you suggest any workaround on this?

That method is there specifically to handle cases where non async resolvers are called inside a running asyncio loop, which django says should be wrapped with `sync_to_async`. Check the [async_safe](https://github.com/blb-ventures/strawberry-django-plus/blob/main/strawberry_django_plus/utils/resolvers.py#L65) implementation for more details.

If you want so support both sync and async with your code, you will have to write some spaghetti code there, unfortunately T_T. I have some utils in this lib that helps with that like the [aio.resolve](https://github.com/blb-ventures/strawberry-django-plus/blob/main/strawberry_django_plus/utils/aio.py#L128) and [aio.resolver](https://github.com/blb-ventures/strawberry-django-plus/blob/main/strawberry_django_plus/utils/aio.py#L207) functions. They will wrap that coroutine and return a coroutine themselves which will get cascading resolved by strawberry itself at the end. You can check some of their usage across this repo

> 3. My initial instinct was to detect whether the type is a subclass of CursorPaginatedList and not have to pass a cursor_pagination=True to the constructor but I could not find a way to detect the type within the init to disable default order and pagination. Also couldn't find a reliable way to detect whether a type is a subclass for that matter. Any suggestions ?

The issue here is that the field gets created before the type annotation is assigned to it, which happens when creating the type itself.

There are some ways around it, like, for example, overriding the `arguments` property and poping those from it, like what I do in [StrawberryDjangoConnectionField](https://github.com/blb-ventures/strawberry-django-plus/blob/main/strawberry_django_plus/field.py#L298)

> 1. While reading through the code to get hints for my implementation I noticed that it's very tightly coupled with the relay implementation which made it kind of hard to figure out which part needed to be re-implemented. Perhaps the relay implementation should be completely separate ?

It actually is. The https://github.com/blb-ventures/strawberry-django-plus/blob/main/strawberry_django_plus/relay.py is a generic relay implementation in which you can also override some of its methods to do a different kind of pagination (e.g. implement a real cursor based instead of the basic offset pagination it uses).

The django type creation checks if it is a subclass of `Node`, and if it is, [it will override those methods](https://github.com/blb-ventures/strawberry-django-plus/blob/main/strawberry_django_plus/type.py#L289) with some that provides better integration with querysets.

> 2. StrawberryDjangoField is a subclass of strawberry_django.field.StrawberryDjangoField which has multiple inheritance on the pagination , filter and ordering classes. It would be nice if a bare minimally working version of StrawberryDjangoField was provided so a user can do his own composition on the field choosing to use , not use or maybe replace some of these classes.

Yeah, I agree. This repo is actually going to be [merged to strawberry_django](https://github.com/blb-ventures/strawberry-django-plus/issues/73) in the future, and when that happens, I plan on refactoring some code to solve some of those legacy issues.
