### ISSUE TITLE
InputMutation / Mutation not working with List return type

### ISSUE THREAD

**Issue by gersmann** [blb-ventures/strawberry-django-plus#162]
Not sure if this is on purpose, I think that an `gql.django.input_mutation` should be able to return a list type. There seems to be something off in schema generation based on the type annotations, the doesn't have a list, but the type itself, and the mutation fails at runtime.

Example:
```
@gql.type
class Foo:
    bar: str

@gql.type
class Mutation:
    @gql.django.input_mutation
    def do_something(self, info: Info, foo: str, bar: str) -> List[Foo]:
        pass
```

results in: 
```
input DoSomethingInput {
  foo: String!
  bar: String!
}

union DoSomethingPayload = Foo | OperationInfo
```

but should result in:
```
"""Input data for `doSomething` mutation"""
input DoSomethingInput {
  foo: String!
  bar: String!
}

union DoSomethingPayload = [Foo] | OperationInfo
```

At runtime the error is:
```
{
  "data": null,
  "errors": [
    {
      "message": "The type \"<class 'list'>\" cannot be resolved for the field \"doSomething\" , are you using a strawberry.field?",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "doSomething"
      ]
    }
  ]
}
```

**Comment by bellini666** [comment]
Hey @gersmann ,

The issue here is probably because of the union that the `input_mutation` creates with `OperationInfo`. The graphql spec only allows unions of types (you can't create a union with lists or scalars), and thus it is failing.

You can try to either return a type that has the list in it or pass `handle_django_errors=False` to the input_mutation so that it will not create the union (but it will not handle `ValidationError`/`PermissionDenied` for you)

**Comment by gersmann** [comment]
That makes sense, thank you. On the other hand, implicitly converting the list return value to it's contained type is maybe a bit too much magic? We can close this ticket though.

**Comment by bellini666** [comment]
> On the other hand, implicitly converting the list return value to it's contained type is maybe a bit too much magic

I agree. The issue is that that part was born that way, so setting `handle_django_errors=False` by default would be a big breaking change.

I'll try to fix all of those issues in the merge to strawberry-graphql-django :)
