### ISSUE TITLE
[ERROR] Error in the project `default`:  Invalid use of @refetchable on fragment 

### ISSUE THREAD

**Issue by ashleyxue529** [blb-ventures/strawberry-django-plus#166]
Trying to implement pagination following https://relay.dev/docs/guided-tour/list-data/pagination/

But on Relay compile, I'm running into this error: 
```
[ERROR] Error in the project `default`: ✖︎ Invalid use of @refetchable on fragment 'FeedTab_brand', check that your schema defines a `Node { id: ID }` interface and has a `node(id: ID): Node` field on the query type (the id argument may also be non-null).
```

I have the types setup correctly afaik. It seems like the compiler is complaining about the fact that GlobalID is used instead of ID as the type. Is that expected? Or is this a bug? Manually replacing GlobalID with ID seems to fix the issue, is there a workaround for this?

Here is my setup:

### RELAY:

```
fragment FeedTab_brand on BrandType @refetchable (queryName: "ExampleQueryName")  {
  feedPosts(first: 10) @connection(key: "FeedTab_feedPosts") {
    edges { node { fields }}
  }
}
```

### DJANGO:

```
@gql.type
class BrandQueries:
    brand: BrandType = relay.node(description="Brand info given a brand ID")


@gql.django.type(Brand)
class BrandType(relay.Node):
    fields: auto
```

### SCHEMA.GRAPHQL
```
type BrandType implements Node {
  id: GlobalID!
}

type Query {
  """Brand info given a brand ID"""
  brand(
    """The ID of the object."""
    id: GlobalID!
  ): BrandType!
}
```

**Comment by bellini666** [comment]
Hi @ashleyxue529 ,

The issue here is that we define the id with the name `GlobalID`, and apparently it really requires it to be defined as `ID`

What you can do is override the it and call it `ID`. Just copy [this code](https://github.com/blb-ventures/strawberry-django-plus/blob/main/strawberry_django_plus/relay.py#L314) and change `name="GlobalID"` to `name="ID"`

Maybe you will need to remove the `ID` provided by `strawberry` from the `DEFAULT_SCALARS_REGISTRY`, but I'm not sure

**Comment by ashleyxue529** [comment]
Ah great thanks! Putting that in my base graphql_schema.py file seems to work.
```
# Sets the name from GlobalID! to ID!
DEFAULT_SCALAR_REGISTRY[relay.GlobalID] = ScalarDefinition(
    # Use the same name/description/parse_literal from GraphQLID as relay
    # specs expect this type to be "ID".
    name="ID",
    description=GraphQLID.description,
    parse_literal=lambda v, vars=None: relay.GlobalID.from_id(
        GraphQLID.parse_literal(v, vars)
    ),
    parse_value=relay.GlobalID.from_id,
    serialize=str,
    specified_by_url="https://relay.dev/graphql/objectidentification.html",
)
```

I also realized that I was missing the `node: Optional[gql.Node] = gql.django.node()` under my Query class, so updating those two things seems to fix it. @bellini666 would it be good to add ` node: Optional[gql.Node] = gql.django.node()` into the base strawberry-django implementation by default? Seems like an easy, but important, thing to miss. 

Thanks a ton for the pointer!

**Comment by bellini666** [comment]
Awesome! I'll close the issue now :)
