### ISSUE TITLE
Strawberry 0.99.0 break this libary

### ISSUE THREAD

**Issue by darwinhace** [blb-ventures/strawberry-django-plus#17]
update strawberry to 0.99.0 break this library

`  File "/home/darwin/.virtualenvs/django4/lib/python3.8/site-packages/strawberry_django_plus/relay.py", line 311, in <module>
    DEFAULT_SCALAR_REGISTRY[GlobalID] = ScalarDefinition(
TypeError: __init__() missing 1 required positional argument: 'specified_by_url'
`
I happened because strawberry introduce new argument 'specified_by_url'

**Comment by bellini666** [comment]
@darwinhace thanks for pointing it out!

Should be fixed in the release 1.3.0 that I'm currently releasing.
