### ISSUE TITLE
Non functional filters for django with relay. 

### ISSUE THREAD

**Issue by robrichter** [blb-ventures/strawberry-django-plus#170]
I use Django with relay. I have a problem with filters that are in schema, but they are completely ignored. 

When I run query all items are returned no matter which attribute I use for filtering. 

I tried to create filter method: filter_order and it is never called. 
```
query MyQuery {
  layers(filters: {order: 2}) {
    edges {
      node {
        order
      }
    }
  }
}
```

I tried to set filters=filters.MapLayerFilter only in  `@gql.django.type(models.MapLayer, filters=filters.MapLayerFilter)`
then only in query `layers: gql.Connection[types.MapLayer] = gql.django.connection(filters=filters.MapLayerFilter)`
Then in both. Nothing works. 

Any idea what am I doing wrong?
```
# MODEL
class MapLayer(models.Model):
    visible = models.BooleanField(default=False)
    opacity = models.FloatField(default=1.0)
    order = models.IntegerField()


# FILTER
@gql.django.filter(model=models.MapLayer, lookups=True)
class MapLayerFilter:
    visible: Optional[bool]
    opacity: Optional[float]
    order: Optional[int]


# TYPE
@gql.django.type(models.MapLayer, filters=filters.MapLayerFilter)
class MapLayer(relay.Node):
    order: gql.auto
    opacity: gql.auto
    visible: gql.auto

    def filter_order(self, queryset, info):
        print("hello from filter_order")


# QUERY
@gql.type
class Query:
    layers: gql.Connection[types.MapLayer] = gql.django.connection(filters=filters.MapLayerFilter)
```

**Comment by bellini666** [comment]
Hey @robrichter . Wow, I accidently broke it and didn't notice

Am pushing a fix ATM, together with some tests to avoid breaking it again in the future :P
