### ISSUE TITLE
resolve_nodes not working when using gql.django.connection ?

### ISSUE THREAD

**Issue by darwinhace** [blb-ventures/strawberry-django-plus#18]
When I try to resolve_nodes to make a custom query, it doesn't affect the result, and when I add the `print` statement on resolve_nodes function, it does not appear on the console.

**Comment by bellini666** [comment]
Hey @darwinhace , can you provide an example of the problem?

**Comment by darwinhace** [comment]
models:
```
class Company(models.Model):
    name = models.CharField(max_length=255)
    is_active = models.BooleanField()
    
class Employee(models.Model):
    company = models.ForeignKey(
        Company, related_name="eployees", on_delete=models.CASCADE
    )
    name = models.CharField(max_length=255)
```
    

type:
```
@gql.django.filter(models.Company, lookups=True)
class CompanyFilter:
    name: gql.auto


@gql.django.type(models.Company, filters=CompanyFilter)
class Company(relay.Node):
    name: gql.auto
    is_active: gql.auto
    employees: List["Employee"]

    @classmethod
    def resolve_nodes(cls, info):
        return Company.objects.filter(is_active=True)


@gql.django.type(models.Employee)
class Employee(relay.Node):
    name: gql.auto
    company: Company

```


schema:
```
@gql.type
class Query:
    companies: relay.Connection[Company] = gql.django.connection()
    employees: relay.Connection[Employee] = gql.django.connection()


schema = gql.Schema(
    query=Query,
    extensions=[
        SchemaDirectiveExtension,
        DjangoOptimizerExtension,
    ],
)

```

when I queried
```
{
  companies {
    edges {
      node {
        id
        name
        isActive
      }
    }
  }
}
```

it returns everything on companies, even on resolve_nodes I only filter is_active = True

or resolve_nodes is ignored when using gql.django.connection ?

one more bug I found when I tried queries
```
{
 companies(filters:{name: { iContains: "spend"}}) {
    edges {
      node {
        id
        name
        isActive
        employees {
          id
          name
        }
      }
    }
  }
}
```

it returns
```
{
  "data": null,
  "errors": [
    {
      "message": "'employees' lookup was already seen with a different queryset. You may need to adjust the ordering of your lookups.",
      "locations": [
        {
          "line": 2,
          "column": 2
        }
      ],
      "path": [
        "companies"
      ]
    }
  ]
}
```

it only happens when I use DjangoOptimizerExtension

**Comment by bellini666** [comment]
Hey @darwinhace ,

What version of this lib are you using? I remember fixing that "lookup was already seen with a different queryset" some days ago.

Also, is there a reason to why you are implementing your own `resolve_nodes`? This extension already implements one for django types and makes sure they are optimized. And it will also not be used for connections, `resolve_connections` is the one that would, but it would be a bit more complex to override.

One possibility to do what you want there would be to define your own nodes resolver that will be used by the connection. Like this:

```python
@gql.type
class Query:
    @gql.django.connection()
    def companies(self) -> Iterable[Company]:
        return Company.objects.filter(is_active=True)
```

It will use that queryset as the base nodes to be used by the connection paginator.

**Comment by darwinhace** [comment]
Thanks for the reply @bellini666, 

I'm using the latest version of this lib
```
strawberry-django-plus==1.3.1
strawberry-graphql==0.99.0
strawberry-graphql-django==0.2.5
```

For resolve_nodes, I just want to keep my code clean on type without adding a new resolver.
If I'm using a custom resolver, I can't use filters and order, I need to manually add filters and order arguments to the resolver.

**Comment by bellini666** [comment]
@darwinhace you could try to override the `resolve_connection` then and call super with the nodes already resolved. For example:

```python
@gql.django.type(models.Company, filters=CompanyFilter)
class Company(relay.Node):
    name: gql.auto
    is_active: gql.auto
    employees: List["Employee"]

    @classmethod
    def resolve_connection(cls, nodes=None, **kwargs):
        if nodes is None:
            nodes = models.Company.objects.filter(is_active=True)
        return super().resolve_connection(nodes=nodes, **kwargs)
```

Please tell me if this works for you

**Comment by darwinhace** [comment]
@bellini666 yes resolve_connection is working, but I will use a custom resolver from your previous suggestion. Since it's cleaner.

But if we can use filters and order arguments on a custom resolver out of the box it will really great.
