### ISSUE TITLE
DeprecationWarning: Event driven styled extensions for on_request_start or on_request_end are deprecated

### ISSUE THREAD

**Issue by blueyed** [blb-ventures/strawberry-django-plus#180]
With https://github.com/strawberry-graphql/strawberry/pull/2428 (in strawberry-graphql 0.159.0) the following deprecation warning is issued:

> DeprecationWarning: Event driven styled extensions for on_request_start or on_request_end are deprecated, use on_operation instead

Patch:
```diff
diff --git i/strawberry_django_plus/optimizer.py w/strawberry_django_plus/optimizer.py
index 549dfa7..f1e06af 100644
--- i/strawberry_django_plus/optimizer.py
+++ w/strawberry_django_plus/optimizer.py
@@ -5,6 +5,7 @@
     Any,
     Callable,
     Dict,
+    Generator,
     List,
     Optional,
     Tuple,
@@ -592,14 +593,14 @@ def __init__(
         self._enable_select_related = enable_select_related_optimization
         self._enable_prefetch_related = enable_prefetch_related_optimization

-    def on_request_start(self) -> AwaitableOrValue[None]:
-        if not self.enabled.get():
-            return
+    def on_request(self) -> Generator[None, None, None]:
+        if enabled := self.enabled.get():
+            optimizer.set(self)

-        optimizer.set(self)
+        yield

-    def on_request_end(self) -> AwaitableOrValue[None]:
-        optimizer.set(None)
+        if enabled:
+            optimizer.set(None)

     def resolve(
         self,
```

The new style appears to be introduced with 0.159.0 only though, so an unconditional patch would require to upper the dependency restriction.

I will ignore this DeprecationWarning in tests for now:
```
[tool:pytest]
filterwarnings =
  error
  ...
  # https://github.com/blb-ventures/strawberry-django-plus/issues/180
  ignore:^Event driven styled extensions for on_request_start:DeprecationWarning:strawberry.extensions.context
```

**Comment by bellini666** [comment]
> The new style appears to be introduced with 0.159.0 only though, so an unconditional patch would require to upper the dependency restriction.

I think it is fine. There's nothing in newer versions that would break strawberry-django-plus, and no reason to not update it. I'm actually using the latest version of both in my projects :)

Feel free to open a PR with the change!
