### ISSUE TITLE
ImportError: cannot import name 'Extension' from 'strawberry.extensions.base_extension'

### ISSUE THREAD

**Issue by scpaes** [blb-ventures/strawberry-django-plus#184]
0.160.0 - 2023-03-08

strawberry-graphql-django [change log](https://github.com/strawberry-graphql/strawberry/blob/main/CHANGELOG.md#01600---2023-03-08) 

"Rename Extension to SchemaExtension to pave the way for FieldExtensions. Importing Extension from strawberry.extensions will now raise a deprecation warning."

**Comment by bellini666** [comment]
Fixed by https://github.com/blb-ventures/strawberry-django-plus/pull/183 and just released a few moments ago :)
