### ISSUE TITLE
Getting `totalCount` for paginated results

### ISSUE THREAD

**Issue by stoicsleuth** [blb-ventures/strawberry-django-plus#190]
I am using the `offset` based pagination in our queries using strawberry-django-plus as stated below -

```
    results: List[ResultNode] = gql.django.field(
           permission_classes=[IsAuthenticated],
           pagination=True,
     )
```

However, this does not give us the total count of items after filters applied, which we need in order to show in our table pagination.
Is there any better way of achieving this apart from overriding `gql.django.field` and adding a `totalCount` attribute to the results?

**Comment by bellini666** [comment]
Hi @stoicsleuth ,

When you return a `list` of elements, it just have the list and no information about pagination.

What I recommend is using a [relay connection](https://blb-ventures.github.io/strawberry-django-plus/quickstart/#relay-support) for that. If gives you everything you need to paginate, and you also have the pagination info, together with `totalCount` in the result.
