### ISSUE TITLE
Optimization doesn't work with two nested fragments

### ISSUE THREAD

**Issue by LucasPickering** [blb-ventures/strawberry-django-plus#203]
First off, as always, thanks for the great work on this. It's made my life so much easier.

I noticed an issue related to the optimizer, similar to #144 - if you make a query with two fragments, where each one has nested fields that need to be merged together, the optimizer doesn't properly merge them before collecting `select_related`/`prefetch_related` fields. Only the second fragment gets its fields picked up, so the fields in the first fragment don't get optimized. Here's an example query for the demo (I populated the DB with one project, one milestone, and two issues for this):

```graphql
query MyQuery {
  issueConn {
    ...IssueConnection2
    ...IssueConnection1
  }
}

fragment IssueConnection1 on IssueTypeConnection {
  edges {
    node {
      issueAssignees {
        id
      }
    }
  }
}

fragment IssueConnection2 on IssueTypeConnection {
  edges {
    node {
      milestone {
        id
        project {
          name
        }
      }
    }
  }
}
```

This generates 4 SQL queries: 
![image](https://github.com/blb-ventures/strawberry-django-plus/assets/2382935/b93b87e7-a9b5-451b-a318-3cbbb029f972)

If you flip the two fragments, like so:

```graphql
query MyQuery {
  issueConn {
    ...IssueConnection2
    ...IssueConnection1
  }
}
```

You get 9 SQL queries: 
![image](https://github.com/blb-ventures/strawberry-django-plus/assets/2382935/601d2e99-289d-4f15-ad5a-bd791cb0003c)

In either case, whichever fragment is included _first_ doesn't get optimized. I did some investigation and it seems related to [this chunk of code](https://github.com/blb-ventures/strawberry-django-plus/blob/470abf531f9a55795efce3daf9a44a3820797418/strawberry_django_plus/utils/inspect.py#L241). When combining two fragments, it properly merges the first set of fields (in this case, the fields inside `edges`), but not the nested level (the fields within `node`), so just second fragment always overwrites the first. I think this code will need some more recursion to get it to work with arbitrary nesting, but I'm not quite sure what that would look like.

**Comment by bellini666** [comment]
Hey @LucasPickering ,

> In either case, whichever fragment is included first doesn't get optimized. I did some investigation and it seems related to [this chunk of code](https://github.com/blb-ventures/strawberry-django-plus/blob/470abf531f9a55795efce3daf9a44a3820797418/strawberry_django_plus/utils/inspect.py#L241). When combining two fragments, it properly merges the first set of fields (in this case, the fields inside edges), but not the nested level (the fields within node), so just second fragment always overwrites the first. I think this code will need some more recursion to get it to work with arbitrary nesting, but I'm not quite sure what that would look like.

Yeah, you are right! I'll try to take a look at this at the weekend. Unless you want to try to tackle this by yourself?

**Comment by LucasPickering** [comment]
@bellini666 I tried briefly to write a fix while I was investigating but couldn't figure it out. Unfortunately I won't have any time soon to try again :(

**Comment by bellini666** [comment]
Think I got it! :)

Will do a new release here, please tell me if it solves the issue for you

**Comment by LucasPickering** [comment]
Looks like it's fixed, thank you!!
