### ISSUE TITLE
Native Django async queries

### ISSUE THREAD

**Issue by moritz89** [blb-ventures/strawberry-django-plus#205]
Wanted to ask whether the native async capabilities of Django introduced in 4.1 are on the roadmap or if they are relevant at all?

**Comment by bellini666** [comment]
Hey @moritz89 ,

This lib already supports async django. If you are talking about the async ORM functions, those in django itself are defined as wrappers around their sync versions using `sync_to_async`, which is basically what this extension also does

**Comment by moritz89** [comment]
Thanks for the clarification!
