### ISSUE TITLE
ManyToMany Relation adds extra "__" to prefetch lookup

### ISSUE THREAD

**Issue by hiporox** [blb-ventures/strawberry-django-plus#21]
Getting the error: `Cannot find '' on Team object, 'team____users' is an invalid parameter to prefetch_related()` when trying to query something like the following:
```graphql
{
  turns(pagination: {limit: 1}) {
    id
    team {
      id
      users {
        id
      }
    }    
  }
}
```

The models are defined with the following relationships:
```python
class Turn(Model):
    team = ForeignKey("Team", null=True)
    ...

class Team(Model):
    users = ManyToManyField("Users")
    ...
```

And the type definitions are as follows:
```python
@gql.django.type(Turn)
class TurnType:
    id: strawberry.ID
    team: Optional[TeamType]

@gql.django.type(Team)
class TeamType:
    id: strawberry.ID
    users: List[UserType]

@gql.djangp.type(User)
class UserType:
    id: strawberry.ID

@strawberry.type
class Query:
    turns: List[TurnType] = gql.django.field()
```

There is no mypy or any other type checker installed and so do not have type hints in any of the model files. I am not sure if that will cause any issues here. The issue is definitely with the `prefetch` configuration with the `Optimizer`, since if you replace the query definition with `strawberry_django.field()`, the code runs fine (but without the optimizations of course).

**Comment by bellini666** [comment]
Thanks for the report! :)

Will be fixed in the next release I'm doing, please reopen if it is not!
