### ISSUE TITLE
Extra prefetch called when using custom filters on related model

### ISSUE THREAD

**Issue by hiporox** [blb-ventures/strawberry-django-plus#23]
Let's say I have the following model:
```python
class Model(models.Model):
    ...

class RelatedModel(models.Model):
    original_model = ForeignKey("app.Model", related_name="related_models")
```

If I implement a type like:

```python
@gql.django.type(Model)
class ModelType:
    id: strawberry.ID
    
    @gql.django.field
    async def related_models(self, info):
          return self.related_models.active()
```

If the optimizer if enabled, this will perform an extra prefetch on the `RelatedModel`, that will then be overwritten by the `self.related_models.active()` call, meaning an unnecessary trip to the DB.

I would propose we add an option to the `OptimizerConfig` to disable certain fields, selects, and prefetches. Something in the form of:

```python
class OptimizerConfig:
    ...
    disabled_only: List[str] = dataclasses.field(default_factory=list)
    disabled_select_related: List[str] = dataclasses.field(default_factory=list)
    disabled_prefetch_related: List[PrefetchType] = dataclasses.field(default_factory=list)
```

This would allow the definition of a new type to be in the form:
```python
@gql.django.type(Model, disabled_prefetches=["related_models")
class ModelType:
   ...
```

**Comment by bellini666** [comment]
Hey @hiporox ,

Although I understand your use case there, I'm thinking how often this happens to justify this change.

I mean, if you have something that can be prefetched with a name of `related_models`, I would say that semantically it is very unlikely that you will want to return anything different than a list/relay connection in its resolver. In your example, it seems to me that the name should be `related_models_active`.

But having said that, right now the optimizer will optimize the field, using hints from the field, then from the `@model_property` and then from inspecting the model field and merge all of those. Instead, we should probably get only the first one of those. So, in your case here, it would not optimize anything (but you could pass hints to the field to have it optimized if you want)

What do you think?

**Comment by hiporox** [comment]
@bellini666 That suggestion sounds like a great fix.

As for the use case I have is applying a filter to the sub-object, where I don't know exactly what the filter will contain. A query like:
```gql
{
  model {
    id
    relatedModels (filters: { ... } ) {
      id
    }
}
```
I am doing this with the following:
```python
from strawberry_django.filters import apply as apply_gql_filter

@gql.django.type(Model)
class ModelType:
    id: strawberry.ID
    
    @gql.django.field
    def related_models(self, info, filter: RelatedModelFilter = UNSET) -> List[RelatedModelType]:
        return apply_gql_filter(filter, self.related_models)
```

I agree that if I knew what the filters that would be applied were, that this would not be necessary, as I could do something like `active_related_models`, but having to name it something like `filtered_related_model` feels a little weird.

**Comment by bellini666** [comment]
@hiporox I tried to implement my suggestion but in the end it would complicate the code a lot because of the automatic field creation by annotations.

I decided to add a new `disable_optimization` keyword to the field, so you can `gql.django.field(disable_optimization=True)` and it should disable it.

Maybe we should revisit this in the future to solve this in a more robust way, but for now this should be enough and should solve your issue. Please reopen this if that's not the case.
