### ISSUE TITLE
filters not showing up

### ISSUE THREAD

**Issue by tasiotas** [blb-ventures/strawberry-django-plus#243]
Hi,

After upgrading to v3, `filters` are not showing up in GraphiQL. They do if I have `order` specified.

with `order`

```python
@gql.django.type(Article, filters=ArticleFilter, order=ArticleOrder)
class ArticleType(gql.relay.Node):
    slug: gql.auto
    title: gql.auto
    ...
```
![image](https://github.com/blb-ventures/strawberry-django-plus/assets/9046931/323cb97d-2cc7-4a38-a06f-13b4f63b5430)

without `order`
```python
@gql.django.type(Article, filters=ArticleFilter)
class ArticleType(gql.relay.Node):
    slug: gql.auto
    title: gql.auto
    ...
```
![image](https://github.com/blb-ventures/strawberry-django-plus/assets/9046931/ee6dbfd2-8249-4a26-8ce2-b2b48b676888)

**Comment by bellini666** [comment]
Hey @tasiotas . I think I found the issue. It will be fixed in the next release I'm doing right now
