### ISSUE TITLE
class inheritance not being detected?

### ISSUE THREAD

**Issue by DavidLemayian** [blb-ventures/strawberry-django-plus#247]
In v3, If I have a class like this:

```py
class CommonType:
  id: strawberry.ID
```

and the model like so:

```py
@gql.django.type(Fruit)
class Fruit(CommonType):
   ...
```

then this does not work:

```gql
{
   fruit {
      id
    }
}
```

works in v2.x so not sure why v3 doesn't work

**Comment by bellini666** [comment]
Hey @DavidLemayian ,

Yeah, that's a regression from v3. I think I know how to fix that, will try to do that soon! :)

**Comment by DavidLemayian** [comment]
Thank you @bellini666  ❤️

**Comment by bellini666** [comment]
@DavidLemayian I just release version 3.0.2 which should fix your issue! Could you comment here if it really fixed or not?

**Comment by DavidLemayian** [comment]
@bellini666 finally managed to test and unfortunately not working.

Not sure if this is useful too - https://github.com/DavidLemayian/strawberry-django-plus/commit/da95d01891490d09ccf1c06a5b742f20d6725ffd

**Comment by bellini666** [comment]
> 

That is very useful! Will take a look at that probably tomorrow for a proper fix

**Comment by bellini666** [comment]
@DavidLemayian OMG, I tested your example and just noticed the reason it didn't work =P

Fields are only inherited from other dataclasses/strawberry types. Meaning your `CommonType` should either be define like:

```python
@dataclasses.dataclass
class CommonType:
    id: strawberry.ID
```

Or

```python
@strawberry.type
class CommonType:
    id: strawberry.ID
```

Testing your example locally I could make the test pass by decorating it with `@dataclasses.dataclass`

**Comment by DavidLemayian** [comment]
Oh wow! Thank you! Will test this later

**Comment by DavidLemayian** [comment]
Yup @bellini666 . This work 🤦  ❤️  

Wishing you a good week ahead
