### ISSUE TITLE
hard dependency on django.contrib.auth

### ISSUE THREAD

**Issue by devkral** [blb-ventures/strawberry-django-plus#249]
The line in utils/typing.py:

UserType: TypeAlias = Union[AbstractUser, AnonymousUser]

requires the inclusion of "django.contrib.auth" in INSTALLED_APPS

it would be better to use the 

AbstractBaseUser of django/contrib/auth/base_user.py as it doesn't require the inclusion and is even the base of AbstractUser, AnonymousUser and an extra UserType is not neccessary.

This also improves the compatibility with 3party user apps

**Comment by bellini666** [comment]
Hey @devkral ,

Thanks for pointing it out. Do you want to open a PR for that?
