### ISSUE TITLE
Interfaces failing with foreign keys

### ISSUE THREAD

**Issue by furious-luke** [blb-ventures/strawberry-django-plus#26]
Hey again! My apologies for issue spamming, but I've come across another problem when dealing with interfaces and polymorphic models. Please consider the following example:

```python
# models.py
class Media(Polymorphic):
    name = models.TextField()

class Movie(Media):
    director = models.TextField()

class Book(Media):
    author = models.TextField()

class Entry(models.Model):
    media = models.ForeignKey(Media)

# schema.py
@gql.django.interface(Media)
class MediaType:
    name: auto

@gql.django.type(Movie)
class MovieType(MediaType):
    name: auto
    director: auto

@gql.django.type(Book)
class BookType(MediaType):
    name: auto
    author: auto

@gql.django.type(Entry)
class EntryType:
    media: MediaType

@gql.type
class Query:
    @gql.django.field
    def get_entry(self, info: Info, id: int) -> EntryType:
        return Entry.objects.get(id=id)
```

So, there's a bit going on there, but the gist is that we have an entry model that has a foreign-key to a polymorphic type which can be either a movie or a book. Up to this point it works as expected, and my GraphQL schema looks correct. However, consider the following query:

```graphql
query entry($id: int) {
  getEntry(id: $id) {
    media {
      __typename,
      name,
      ... on MovieType {
        director
      },
      ... on BookType {
        author
      }
    }
  }
}
```

This query will fail for every foreign-key that is not a movie, as it will always try to resolve the first type in the interface instead of determining the correct type of the Django model and resolving only that interface sub type.

I've done a bit of digging around and it appears that the Django GraphQL field resolvers aren't converting Django models to Strawberry types (please correct me if I'm wrong). This could be the cause of the issue, as [in the Strawberry documentation](https://strawberry.rocks/docs/types/interfaces#resolving-an-interface) it mentions that we may need to return Strawberry types in order to correctly identify the interface sub type.

**Comment by bellini666** [comment]
Hey @furious-luke ,

> I've done a bit of digging around and it appears that the Django GraphQL field resolvers aren't converting Django models to Strawberry types (please correct me if I'm wrong).

You are correct! This is actually the behaviour from the official [strawberry-graphql-django](https://github.com/strawberry-graphql/strawberry-graphql-django), and from all other integrations (e.g. pydantic) if I'm not mistaken.

What probably needs to be done here is to somewhat map the model to the type itself so that the interface gets resolved correctly.

Could you provide a minimal runnable example that I can use for testing? With that I might be able to solve this issue.

**Comment by bellini666** [comment]
@furious-luke I think I fixed this issue in the latest release here. Going to close the issue, but please reopen it if that's not the case
