### ISSUE TITLE
nested connection not working ? 

### ISSUE THREAD

**Issue by darwinhace** [blb-ventures/strawberry-django-plus#3]
Hi, I love this package, but when I play around and tried clone test models on this repo and tried to query this:

`{
  projectConn {
    edges {
      cursor
      node {
        id
        name
        milestonesConn {
          edges {
            cursor
            node {
              id
              name
            }
          }
        }
      }
    }
  }
}
`

results errors

`{
  "data": null,
  "errors": [
    {
      "message": "'Project' object has no attribute 'milestones_conn'",
      "locations": [
        {
          "line": 8,
          "column": 9
        }
      ],
      "path": [
        "projectConn",
        "edges",
        0,
        "node",
        "milestonesConn"
      ]
    }
  ]
}`

**Comment by bellini666** [comment]
Hey @darwinhace ,

Happy to know you liked it :)

This project is still very young and I'm doing a lot of developed on top of it those days, so you should see things get better and better each day. I also need to adjust the testing/demo project.

Having said that, I don't think nested connections was something I tested. It should work though, but maybe I need to consider that corner case for things like queryset optimization.

I'll take a look at this soon! In the meantime, feel free to open more issues if you are having any other issues with this package.

**Comment by bellini666** [comment]
@darwinhace no need to close the issue, it is still valid.
Either way, np because I'm going to look at this today :)
