### ISSUE TITLE
Optimizer Doesn't Work With Repeated Items in Query Top Level

### ISSUE THREAD

**Issue by hiporox** [blb-ventures/strawberry-django-plus#33]
If you have the following query:
```gql
query PropertyQuery {
  properties {
    id
    shortName
    __typename
  }
  properties {
    id
    longName
  }
}
```
The optimizer breaks down and only optimizes the first of the top level items in that query. While this is an unlikely query to ever run in reality, this behavior seems wrong

**Comment by hiporox** [comment]
For a little extra context on the use case for this: I am using the optimizer to optimize queries that are being managed by a `DataLoader`. The `DataLoader` performs a subquery, and runs the optimizer over the queryset before converting that QS into a list to be able to distribute its results out to the functions that called it

**Comment by bellini666** [comment]
Hahaha indeed very unlikely, but the fix is good. Going to merge it and make a new release :)
