### ISSUE TITLE
@gql.django.input_mutation cannot return Interface or Union

### ISSUE THREAD

**Issue by yergom** [blb-ventures/strawberry-django-plus#36]
Returning an interface or Union from a input_mutation fails with callstack:

```
File "/.venv/lib/python3.8/site-packages/strawberry/schema/schema.py", line 85, in __init__
    self._schema = GraphQLSchema(
  File "./venv/lib/python3.8/site-packages/graphql/type/schema.py", line 226, in __init__
    collect_referenced_types(mutation)
  File "/.venv/lib/python3.8/site-packages/graphql/type/schema.py", line 432, in collect_referenced_types
    for field in named_type.fields.values():
  File "/usr/local/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/.venv/lib/python3.8/site-packages/graphql/type/definition.py", line 802, in fields
    raise cls(f"{self.name} fields cannot be resolved. {error}") from error
TypeError: Mutation fields cannot be resolved. 
```

I've tried to simplify the reproduction as much as possible:

```python
from strawberry_django_plus import gql
@gql.interface
class AnInterface:
    name:str

@gql.type
class Query:
    @gql.field
    def empty(self) -> str:
        return ""

@gql.type
class Mutation:
    @gql.django.input_mutation
    def my_mutation(self) -> AnInterface:
        pass

schema = gql.Schema(
    query=Query,
    mutation=Mutation,
)
```

Note that using strawberry mutations works fine:

```python
from strawberry_django_plus import gql
@gql.interface
class AnInterface:
    name:str

@gql.type
class Query:
    @gql.field
    def empty(self) -> str:
        return ""

@gql.type
class Mutation:
    @strawberry.mutation #<----- Changed
    def my_mutation(self) -> AnInterface:
        pass

schema = gql.Schema(
    query=Query,
    mutation=Mutation,
)
```

**Comment by bellini666** [comment]
Hey @yergom ,

Sorry for the delay, I was traveling outside the country.

So, the issue is that `input_mutation` tries to convert the output type to be a union of it with `OperationInfo` to handle ValidationError/PermissionError, but it failed to create a union with an interface.

What you can easily do here is to use `gql.relay.input_mutation` directly. The only downside is basically the lack of that union for errors, but since you want to return an interface it would not be possible either way.

Can you confirm me if that works?

**Comment by bellini666** [comment]
@yergom there's a new `handle_errors` argument that you can pass to both `gql.django.mutation` and `gql.django.input_mutation`. If you pass `handle_errors=False` they will not try to create a union of the return type with `OperationInfo`, and you might be able to return the interface that you want.

Please tell me if that doesn't solve your issue properly and reopen this issue.
