### ISSUE TITLE
gql.django.connection fails to use the right get_queryset when set as a field

### ISSUE THREAD

**Issue by devkral** [blb-ventures/strawberry-django-plus#46]
Problem:
if django.connection is applied on a field on a django node object the wrong get_queryset is used.

here an reduced excerpt from my project

```

@gql.django.type(ContentReference, filters=ContentReferenceFilter)
class ContentReferenceNode(relay.Node):
    def get_queryset(...):
       ....
@gql.django.type(Content, name="Content", filters=ContentFilter)
class ContentNode(relay.Node):
    references: relay.Connection[ContentReferenceNode] = gql.django.connection(
        filters=ContentReferenceFilter
    )

    def get_queryset(...):
       ....

```

the field references uses the get_queryset from ContentNode instead of ContentReferenceNode.

**Comment by devkral** [comment]
ask if you have questions,  I was in hurry

**Comment by bellini666** [comment]
@devkral I did a fix in the latest release, I think it may have fixed this issue. Can you confirm to me?

**Comment by devkral** [comment]
sry for the late answer, from what I debugged, I think so.
I will revert my workaround in near future and open new issues in case of errors
