### ISSUE TITLE
Typo in default querying methods for relay

### ISSUE THREAD

**Issue by Bahrom** [blb-ventures/strawberry-django-plus#49]
Hello,

There is a typo in checking default querying methods for relay:

```python
if not _has_own_node_resolver(cls, "resolve_connection_resolver"):
      cls.resolve_connection = types.MethodType(
          lambda *args, **kwargs: resolve_connection(
              *args,
              filter_perms=True,
              **kwargs,
          ),
          cls,
  )
```

Typo in "resolve_connection_resolver".  I think it should be "resolve_connection"

**Comment by bellini666** [comment]
Hey @Bahrom . You are right, thanks for pointing it out!
Going to release a fix in a few minutes for it
