### ISSUE TITLE
missing node from edges when using arguments "last" and "before"

### ISSUE THREAD

**Issue by darwinhace** [blb-ventures/strawberry-django-plus#5]
hey @bellini666, when using arguments {last: 2, before: "..."}, one node missing from edges:

before using arguments:
![image](https://user-images.githubusercontent.com/76155308/152907069-9db9df41-3baf-4bbe-8c7e-52145c2585a0.png)

after using arguments:
![image](https://user-images.githubusercontent.com/76155308/152907165-0c5c2d7e-685e-4ff0-9402-1a5e703ab96f.png)

cursor: "YXJyYXljb25uZWN0aW9uOjE=" missing from edges,

when I remove "-1" from this code on Connection it is work as expected

```
  if before:
            before_type, before_parsed = from_base64(before)
            assert before_type == _connection_typename
            end = min(end, int(before_parsed) - 1)
```

![image](https://user-images.githubusercontent.com/76155308/152913025-c8281849-eba8-407e-ba36-0d0cc9ec350e.png)

**Comment by bellini666** [comment]
@darwinhace when I fixed the previous issue, I naively changed before, forgetting that slices doesn't include the latest index.

Just fixed it and released the version 0.8.1. Please, tell us if you find any other issues with this lib.
