### ISSUE TITLE
Add fields on a relay connection?

### ISSUE THREAD

**Issue by eloff** [blb-ventures/strawberry-django-plus#61]
Is there a way to customize the relay connection type to add additional fields?

For example in my graphene schema I have a custom Connection subclass that adds a completed_count field (similar to total_count, but for a filtered subset of the nodes with is_cancelled=False)

This is possible with strawberry itself, but I'm not sure how to do it when using relay.connection from this repo.

Django Graphene code:
```
 class HqOrganizationConnection(relay.Connection):
     class Meta:
         node = OrganizationType

     total_count = graphene.Int()
     completed_count = graphene.Int()

     class Arguments:
         getHqOrganizationRequest = GetHqOrganizationRequest()

     def resolve_total_count(root, info):
         return root.iterable.count()

     def resolve_completed_count(root, info):
         return root.iterable.filter(is_cancelled=False).count()
```

**Comment by bellini666** [comment]
Hi @eloff ,

Currently you would need to implement your own `Edge` and `Connection` classes and override their logic. But I'm thinking in how to make that relay implementation more generic to allow things like what you want to do.

I'll probably take a look at this soon

**Comment by eloff** [comment]
Ok, good to know. I'll come up with a temporary workaround for now, but I'll revisit it when you close this ticket.

**Comment by K0Te** [comment]
More generic connections would simplify migration from `graphene-django`.
I am currently migrating project that uses multiple subtotals in connections.
For example:
```
class AccountClientConnection(Connection):
    total_account_clients = graphene.Int()
    total_active_account_clients = graphene.Int()
    active_clients_count = graphene.Int()
```
Such use-case is trivial with  `graphene-django` `connection_class`, but complicated with the current connection implementation in strawberry.

**Comment by bellini666** [comment]
@K0Te I just made this change (https://github.com/blb-ventures/strawberry-django-plus/commit/0762f40af0e3219bf395af9d8d3080a630e710fb) which got released in 1.23.

It allows to define a custom `Connection` class for a `Node`, similar to how graphene does. It also allows the `Connection` to define a custom `Edge`.

Do you think this is enough?

**Comment by dennisv** [comment]
@bellini666 I'm trying to add some fields to a connection as well and can't seem to get it to work using `CONNECTION_CLASS`

Could it be that it is still always using the default Connection because of this line?
https://github.com/blb-ventures/strawberry-django-plus/blob/2931b1beebc9b5cc01c4721fe1542ec967255fa3/strawberry_django_plus/relay.py#L951

I'm trying it like this:
```python
@gql.django.type(models.ObjectType)
class ObjectType(gql.Node):
    name: gql.auto

@gql.type
class TestObjectTypeConnection(gql.Connection):
    test: str

ObjectType.CONNECTION_CLASS = TestObjectTypeConnection

@gql.type
class ObjectTypeQuery:
    @gql.connection
    def object_types(
        self,
        ...
    ) -> Iterable[ObjectType]:
        ...
```

But the test field does not show up in graphiql and returns "Cannot query field 'test' on type 'ObjectTypeConnection'."

**Comment by bellini666** [comment]
Hey @dennisv ,

I just noticed that the field was not using the `CONNECTION_CLASS` to create itself.
I just published the version 1.25.1, which should solve this issue. Can you please try to use it and confirm to me if it works?

**Comment by dennisv** [comment]
@bellini666 I get a bit further now, but it's now throwing the following:
`TypeError: <class '[...].TestObjectTypeConnection'> is not a generic class`

**Comment by bellini666** [comment]
@dennisv you need to define your connection as a generic class, just like the original, and pass the `NodeType` captured by the Generic in `Connection`, just like this:

```python
@gql.type
class CustomConnection(Generic[NodeType], Connection[NodeType]):
    ...
```
