### ISSUE TITLE
Support offset based pagination

### ISSUE THREAD

**Issue by yergom** [blb-ventures/strawberry-django-plus#65]
The current relay.Connection is based on cursor pagination, which works great for use cases like infinite scrolling. However, in many business applications end-users expect offset based pagination: They want to see the total number of pages, and be able to jump to a specific page. Although this comes with its own problems (it could be that a user sees the same item in two pages), it's still a very common use case. Would you consider implementing such a Connection?

**Comment by bellini666** [comment]
Hi @yergom,

The current relay implementation is actually a mix of both. Although it is exposed as a cursor based pagination, it uses an offset strategy. The total number of results is currently exposed at the connection, so you can use that to know the number of pages.

Just like I mentioned [in this issue](https://github.com/blb-ventures/strawberry-django-plus/issues/61), I'm trying to think of a good way to create a generic solution that could fit both approaches, and also allow the `Edge`/`Connection` to be easily expanded by the user. I'm not having much time to work on this right now, but hopefully I'll have next month.

**Comment by theGleam** [comment]
Any luck with this, @bellini666?

I am happy to help. Would like to start from where you currently are with it.

**Comment by bellini666** [comment]
Hey @theGleam ,

Don't know what actually needs to be implemented for this, since the current relay implementation uses offset based pagination by default. I also already made some changes to allow someone to easily override it to implement a custom cursor pagination as needed.

But if there's anything else missing still, feel free to open a PR and I'll gladly review it :)

**Comment by tasiotas** [comment]
hi @bellini666 ,

If current implementation already has offset support, how can I pass it query? I can only see cursor parameters, no offset.

![image](https://github.com/blb-ventures/strawberry-django-plus/assets/9046931/d5ec47e8-2dbe-465c-bc33-06607364ca3e)

shouldnt there be `offset` as well?

Thank you

**Comment by tasiotas** [comment]
gotcha! thank you
