### ISSUE TITLE
strawberry-django filters and order not working on relay queries ?

### ISSUE THREAD

**Issue by darwinhace** [blb-ventures/strawberry-django-plus#7]
are strawberry-django filters and order not working on relay queries?

I'm using 

```
@gql.django.filters.filter(models.Company)
class CompanyFilter:
    id: gql.auto
    name: gql.auto

@gql.django.ordering.order(models.Company)
class CompanyOrder:
    id: gql.auto
    name: gql.auto


@gql.django.type(models.Company, filters=CompanyFilter, order=CompanyOrder)
class Company(relay.Node):
    id: gql.auto
    name: gql.auto
    is_god: gql.auto
    child_companies: List["ChildCompany"]

@gql.type
class Query:
    company: Optional[types.Company] = relay.node()
    companies: relay.Connection[types.Company] = relay.connection()

```

there are no arguments filters and order on companies type

![image](https://user-images.githubusercontent.com/76155308/153871602-17e2bc8c-3180-49f5-bee4-3b6977000c98.png)

**Comment by bellini666** [comment]
Hey @darwinhace . Hrm, I don't think I implemented that yet. I'll add support for filtering and ordering this week though :)

**Comment by darwinhace** [comment]
@bellini666 thanks for your reply, I thought it's already implemented :stuck_out_tongue_closed_eyes:

 I will wait for the implementation, I close this issue now.

**Comment by bellini666** [comment]
@darwinhace no need to close the issues, because it is actually valid and I can close them once they are solved :)
