### ISSUE TITLE
Query optimizer extension in docs does not work

### ISSUE THREAD

**Issue by ccsv** [blb-ventures/strawberry-django-plus#74]
So I tried adding the query optimizer using the instructions in the docs:

```
import strawberry
from strawberry_django_plus import gql
from strawberry_django_plus.optimizer import DjangoOptimizerExtension

schema = strawberry.Schema(query=Query, mutation=Mutation, 
    extension=[DjangoOptimizerExtension,]
    )
```

And I got the following error:
`TypeError: Schema.__init__() got an unexpected keyword argument 'extension'`

Also tried changing 

```
schema = strawberry_django_plus.Schema(query=Query, mutation=Mutation, 
    extension=[DjangoOptimizerExtension,]
    )
```
    
and still got the same error:
`
AttributeError: module 'strawberry_django_plus' has no attribute 'Schema'`

**Comment by bellini666** [comment]
Hi @ccsv ,

In your first example there's a typo. The parameter is called `extensions` (with an `s` at the end) and not `extension`.

The second example is wrong because we don't have a custom schema, it is the `Schema` from `strawberry` that should be used.

**Comment by bellini666** [comment]
Going to close this as it seems it is just a type issue. But please reopen if that is not the case.

**Comment by ccsv** [comment]
@bellini666  Oh thanks.
