### ISSUE TITLE
The return type of the mutation

### ISSUE THREAD

**Issue by Luferov** [blb-ventures/strawberry-django-plus#79]
Mutations return the Union type, and this makes returning scalars more difficult. I just wanted to know what was the reason for such a decision?

https://github.com/blb-ventures/strawberry-django-plus/blob/e1578a2ae2393bf29c6d111180a1460cf7c1542a/strawberry_django_plus/mutations/fields.py#L130-L132

**Comment by bellini666** [comment]
Hi @Luferov ,

The mutations in this lib by default creates a union of your return type and `OperationInfo`, which contains errors inside it in case any `ValidationError` happens.

This is following the [pattern suggested by the strawberry docs](https://strawberry.rocks/docs/guides/errors#expected-errors).

You can force it to not create that union by passing `handle_django_errors=False` to the field.

Does that work for you?

**Comment by zvolsky** [comment]
Hi bellini666, thank you.
My frontend developer requires just this, ie. return the plain error.
However I don't know **where or how** could I apply `handle_django_errors=False`.
I create fields like so:
```
@gql.type
class Mutation:
    delete_map: types.Map = gql.django.delete_mutation(gql.NodeInput)

```
Could you give an example how to do it or is it too difficult in such case?

**Comment by bellini666** [comment]
Hey @zvolsky , I added the possibility to pass `handle_django_errors=False` to CRUD mutations. That means you can do `gql.django.delete_mutation(gql.NodeInput, handle_django_errors=False)` and it should work.

The fix is in the latest release. Please reopen the issue if that doesn't solve your problem

**Comment by zvolsky** [comment]
But... I'm sorry, I'm testing more now.

**Comment by zvolsky** [comment]
I cannot reopen (because of GiitHub rights/rules). Should I reopen as New Issue?

**Comment by bellini666** [comment]
@zvolsky I juyst noticed I missed one thing in there, which should be solved in the release I just made. Please tell me if that is not the case :)

**Comment by zvolsky** [comment]
Hi bellini, unfortunately in 1.20 I cannot import gql:
Python 3.10.5 (main, Jun 20 2022, 12:58:22) [GCC 10.2.1 20210110]

```
In [1]: from strawberry_django_plus import gql
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-c8a7c5517f31> in <cell line: 1>()
----> 1 from strawberry_django_plus import gql

~/tm/dmx/dmx-server/.venv/lib/python3.10/site-packages/strawberry_django_plus/gql/__init__.py in <module>
     45 from strawberry_django_plus.utils import aio, resolvers
     46 
---> 47 from . import django
     48 
     49 if TYPE_CHECKING:

~/tm/dmx/dmx-server/.venv/lib/python3.10/site-packages/strawberry_django_plus/gql/django.py in <module>
     14 
     15 from strawberry_django_plus import mutations, types
---> 16 from strawberry_django_plus.field import connection, field, node
     17 from strawberry_django_plus.filters import filter
     18 from strawberry_django_plus.mutations.fields import create as create_mutation

~/tm/dmx/dmx-server/.venv/lib/python3.10/site-packages/strawberry_django_plus/field.py in <module>
     45 from . import relay
     46 from .descriptors import ModelProperty
---> 47 from .optimizer import OptimizerStore, PrefetchType
     48 from .permissions import filter_with_perms
     49 from .utils import resolvers

~/tm/dmx/dmx-server/.venv/lib/python3.10/site-packages/strawberry_django_plus/optimizer.py in <module>
     36 from strawberry.utils.await_maybe import AwaitableOrValue
     37 from strawberry_django.fields.types import resolve_model_field_name
---> 38 from typing_extensions import TypeAlias, assert_never, assert_type
     39 
     40 from .descriptors import ModelProperty

ImportError: cannot import name 'assert_type' from 'typing_extensions' (/home/mirek/tm/dmx/dmx-server/.venv/lib/python3.10/site-packages/typing_extensions.py)

```

**Comment by zvolsky** [comment]
Works perfect! Thanks!
(temporary I reported about a problem, but this was on my side: too old typing-extensions)

**Comment by zvolsky** [comment]
If you want fix the dependency info for typing-extensions: 4.1.1 fails, 4.2.0 and newer (4.3.0) works.
