### ISSUE TITLE
Mutation require ID 

### ISSUE THREAD

**Issue by ccsv** [blb-ventures/strawberry-django-plus#82]
I found that if you add id into the fields for the graphql types like this:

```
@gql.django.type(models.Client)
class Client:
    id:  gql.auto
    name: gql.auto
    notes:  gql.auto

@gql.django.input(models.Client)
class ClientInput:
    id:  gql.auto
    name:  gql.auto
    notes:  gql.auto
```

When you try to write a mutation in the graphiql it has id as a required field instead of have django automatically create them. 

This means mutations like this would not work because it does not have an id field for the input data:

```
mutation newClient ($name:String!) {
  createClient(data: {name: $name}) {
    id
    name
  }
}
```

**Comment by bellini666** [comment]
Hey @ccsv ,

This is as intended. You should have different inputs for creation and edition, that's the reason we have a `partial` type, which converts forces `gql.auto` into non-mandatory fields, different from the input which will consider if the field can be `blank` or not. For the creation input you should not have an id, but for the partial it should be mandatory

Take a look [at the demo](https://github.com/blb-ventures/strawberry-django-plus/blob/main/demo/schema.py#L267) which has some use cases of this (I need to write some more though =P)

**Comment by ccsv** [comment]
@bellini666  I tried the mutations with nested foreign keys and eliminated the IDs:
```

@gql.django.input(models.Address)
class AddressCreateInput:
    name: gql.auto
    notes: gql.auto


@gql.django.input(models.Client)
class ClientInput:
    address:'AddressCreateInput'
    name: gql.auto
    reference:gql.auto


createAddress: Address =gql.django.create_mutation(AddressCreateInput)
createClient: Client =gql.django.create_mutation(ClientInput)
```

If I create a mutation on graphiql it will not create the nested foreign key model instead the data is returned as null:


```
mutation MyMutation {
  __typename
  createClient(input: {address: {name: "sss"}, name: "sss", reference: "A"}) {
    ... on Client {
      id
      email
      address {
        id
        name
        notes
      }
      name
      reference
    }
  }
}

{
  "data": {
    "__typename": "Mutation",
    "createClientEntity": {
      "id": "8",
      "address": null,
      "name": "sss",
      "reference": "A"
    }
  }
}
```

**Comment by bellini666** [comment]
Hey @ccsv , that's strange, your code should work.

I'll try to take a look at it either today or tomorrow and write an example and a test for that case. It should work!

**Comment by bellini666** [comment]
Hey @ccsv . I just noticed that nested creation was only working for m2m. I [just added support for foreign keys](https://github.com/blb-ventures/strawberry-django-plus/commit/a2369ecd4078e0e3f358fd8aa8876f8b0590f756) and it is available in the release I just made.

Please tell me if it fixes your issue.
