### ISSUE TITLE
optimizer: ability to provide Prefetch object using lambda

### ISSUE THREAD

**Issue by wodCZ** [blb-ventures/strawberry-django-plus#83]
Hello 👋 
First of all, thank you for the library, it helped my greatly with rewriting my project from graphene.

On that note, we've been using graphene-django-optimizer to optimize some complex queries. In most of our cases the required Prefetch is dependent on the context — filter only `info.context.request.user`'s nodes.

This was achievable with graphene optimizer's [lambda prefetch feature](https://github.com/tfoxy/graphene-django-optimizer#:~:text=Finally%2C%20if%20your%20field%20has%20an%20argument%20for%20filtering%20results%2C%20you%20can%20use%20the%20prefetch_related%20argument%20with%20a%20function%20that%20returns%20a%20Prefetch%20instance%20as%20the%20value.).

A sample from our model in graphene:
```py
class StoryNode(gql_optimizer.OptimizedDjangoObjectType):
    ...
    
    commented_on_by_user = gql_optimizer.field( # field definition
        graphene.Boolean(required=True),
        prefetch_related=lambda info, *args, **kwargs: Prefetch(
            "comments",
            queryset=models.StoryComment.objects.get_queryset().filter(author_id=info.context.user.id),
            to_attr="my_comments",
        ),
    )


    def resolve_commented_on_by_user(self: Meta.model, info): # resolver
        return (
            len(self.my_comments) > 0
            if hasattr(self, "my_comments")
            else self.comments.filter(author_id=info.context.user.id).exists()
        )
```

Now with strawberry:
```py
@gql.django.type(models.Story)
class StoryNode(gql.relay.Node):

    @gql.django.field()
    def commented_on_by_user(self: models.Story, info: Info) -> bool:
        return self.comments.filter(author_id=info.context.request.user.id).exists()

@gql.django.type(models.Space)
class SpaceNode():
    @gql.django.connection(prefetch_related=["story_set"])
    def stories(self: models.Space) -> Iterable[nodes.StoryNode]:
        return self.story_set.get_queryset()

@gql.type()
class SpaceQueries:
    space: SpaceNode = gql.relay.node(permission_classes=[utils.IsAuthenticated])
```

which obviously causes n+1 issue when fetching multiple stories.

Is there currently a way to optimize such schema? Or is there an easy way to extend the current `prefetch_related` argument on `gql.django.connection` with `lambda info, parent_id: Prefetch(...)` support?

Thanks!

~~Edit: I'm running some testing queries now and I can't get the optimizer working on some queries. My guess is that the optimizer doesn't support relay connections and doesn't catch back up deeper in the schema once it meets the connection in the tree?~~ — Not sure what was wrong, but relay is getting optimized.

**Comment by bellini666** [comment]
Hey @wodCZ . The `prefetch_related` supports passing `Prefetch` to it. It will also merge 2 similar prefetches and optimize the prefetched objects if needed

Could you try it and tell me if it works? The optimizer here covers a lot more corner cases than `graphene-django-optimizer` does.

**Comment by wodCZ** [comment]
@bellini666 the problem is that I need access to `info` to construct the `Prefetch` object:
```py
Prefetch(
    "comments",
    queryset=models.StoryComment.objects.get_queryset().filter(
        author_id=info.context.user.id
        #          ^ I need to filter the prefetched queryset by the user making the request 
    ),
    to_attr="my_comments", 
)
```

which I believe I can't achieve with *static* Prefetch like this?
```py
@gql.django.type(models.Story)
class StoryNode(gql.relay.Node):

    @gql.django.field(prefetch_related=[
        Prefetch(
            "comments",
            queryset=models.StoryComment.objects.get_queryset().filter(
                author_id=info.context.user.id
                #          ^ unresolved reference 'info' 
            ),
            to_attr="my_comments", 
        )
    ])
    def commented_on_by_user(self: models.Story) -> bool:
        return len(self.my_comments) > 0
```

**Comment by bellini666** [comment]
@wodCZ ohhh I see now what you need.

I'll try to add support for that by either today or tomorrow if I have some time

**Comment by bellini666** [comment]
Hey @wodCZ . I just added support for that and it is available in the release I just made.

Please tell me if it works the way you need it

**Comment by wodCZ** [comment]
Incredible work @bellini666, thanks for super fast resolution. So far it works exactly how I need 🚀
