### ISSUE TITLE
Strawberry 0.121.0 breaks relay/Django integration

### ISSUE THREAD

**Issue by taobojlen** [blb-ventures/strawberry-django-plus#90]
I have the following types/queries based on a Django model called `Action`:

```python
@gql.django.type(models.Action)
class ActionType(relay.Node):
    name: gql.auto
    description: gql.auto
    organization: gql.auto
    created_by: gql.auto

@gql.type
class Query:
    action: Optional[ActionType] = relay.node()
    actions: relay.Connection[ActionType] = relay.connection()
```

When I use Strawberry 0.121.0 and attempt either of these queries, I get the following error:

```
{
  "data": null,
  "errors": [
    {
      "message": "'NoneType' object has no attribute 'actions'",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "actions"
      ]
    }
  ]
}
```

The error is arising in strawberry's `schema_converter.from_resolver`, in the `_get_result` function. the `source` argument seems to be `None` there.

When I downgrade to Strawberry 0.120.0, everything works fine!

**Comment by bellini666** [comment]
Hey @taobojlen . Yeah, the change from strawberry 1.121 broke how this lib works.

We are discussing how to workaround that [in this PR](https://github.com/strawberry-graphql/strawberry/pull/2038). Hopefully it will be fixed soon :)

**Comment by bellini666** [comment]
@taobojlen @devkral and anyone following this, strawberry has released a fix for this. Make sure to use its latest version :)
